// Hyperion: drydock tab (ship persistence Cycle 5).
using Content.Shared._Hyperion.ShipSize;
using Content.Shared._NF.Shipyard.BUI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._NF.Shipyard.UI;

[GenerateTypedNameReferences]
public sealed partial class DrydockShipRow : PanelContainer
{
    public Guid ShipId;

    public DrydockShipRow(StoredShipInfo ship)
    {
        RobustXamlLoader.Load(this);

        ShipId = ship.ShipId;
        ShipName.Text = ship.Name;
        SizeClassLabel.Text = ((ShipSizeClass) ship.SizeClass).ToString();
    }
}
